name: mega_ecommerce_app
description: "Mega Ecommerce App."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  get_it: ^9.2.0
  internet_connection_checker: ^3.0.1
  http: ^1.6.0
  dio: ^5.9.0
  dartz: ^0.10.1
  google_fonts: ^6.3.2
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4
  flutter_localizations:
    sdk: flutter
  intl: any
  pin_code_fields: ^8.0.1
  flutter_svg: ^2.2.2
  responsive_framework: ^1.5.1
  shared_preferences: ^2.5.3
  pretty_dio_logger: ^1.4.0
  flutter_secure_storage: ^10.0.0
  flutter_image_slideshow: ^0.1.6
  image_picker: ^1.2.1
  path: ^1.9.1
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1
  flutter_local_notifications: ^19.5.0
  cloud_firestore: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true
  assets:
     - assets/images/
     - assets/fonts/
     - assets/icons/

  fonts:
    - family: inter
      fonts:
        - asset: assets/fonts/inter/Inter_24pt-Black.ttf
          weight: 900
        - asset: assets/fonts/inter/Inter_24pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter_24pt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/inter/Inter_24pt-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/inter/Inter_24pt-Light.ttf
          weight: 300
        - asset: assets/fonts/inter/Inter_24pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter_24pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter_24pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter_24pt-Thin.ttf
          weight: 100

  generate: true


flutter_native_splash:
  color: "#3D93F8"
  image: assets/images/native_splash.png
  android: true
  ios: true
  android_12:
    color: "#3D93F8"
    image: assets/images/native_splash.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/app_icon.png

  adaptive_icon_background: "#3D93F8"
  adaptive_icon_foreground: assets/images/app_icon.png

